;Switch science ESP32
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; 無印ESP32で最も安定する書き込み設定
board_build.flash_mode = dio
board_build.f_flash = 40000000L